# Generated by Django 4.2.5 on 2023-12-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Cliente',
        ),
    ]
